# Generated by Django 2.0.1 on 2018-01-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1200)),
                ('refresh_token', models.CharField(max_length=100)),
                ('token_type', models.CharField(max_length=20)),
                ('xoauth_yahoo_guid', models.CharField(max_length=20)),
            ],
        ),
    ]
